version: '3.8'

services:
  postgres-db:
    image: postgres:14.3 # Puedes cambiar "16" por "latest" o la versi√≥n que necesites
    container_name: postgres_db_pruebas
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123*
      POSTGRES_DB: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local